[package]
name = "rustlog"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
ctrlc = "3.4"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
